"""
tests/medium_loop_manual.py
============================
One-shot manual exercise of _medium_loop_cycle() with controlled mock data.

Scenario
--------
- Watchlist: 2 Tier 1 symbols (AAPL, TSLA) + 1 Tier 2 (NVDA — should NOT be scanned)
- Portfolio: 1 open position (MSFT — included in scan even though not on watchlist)
  So scan list = [AAPL, TSLA, MSFT]
- YFinanceAdapter.fetch_bars mocked to return real-shaped 100-row DataFrames for
  each of those 3 symbols.
- ReasoningCache seeded with a plausible Claude result (as if slow loop ran 5 min ago)
  containing 2 opportunities: AAPL (conviction 0.78) and TSLA (conviction 0.65).
- AlpacaBroker.get_account and place_order mocked.

Expected behaviour
------------------
A. TA computed for all 3 symbols — composite scores present, no NaN.
B. Entry signals generated by strategies for at least the symbols with
   favourable indicators (depends on synthetic data shape).
C. Ranker sees Claude opportunities + fresh TA, produces a scored list.
D. The parsed_response is read correctly (not the top-level cache envelope)
   — if the raw cache record is passed instead of parsed_response, opportunities
   will be empty and this assertion will fail.
E. Top opportunity (if any passes filters) triggers fill_protection gate check
   and, if clear, attempts place_order.
F. evaluate_position() runs on the MSFT position without error.

Run with:
    PYTHONPATH=. python ozymandias/tests/medium_loop_manual.py
"""
from __future__ import annotations

import asyncio
import json
import logging
import sys
import tempfile
import traceback
from datetime import datetime, timezone, timedelta
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import numpy as np
import pandas as pd

logging.basicConfig(
    level=logging.DEBUG,
    format="%(levelname)-8s %(name)s  %(message)s",
    stream=sys.stdout,
)
log = logging.getLogger("medium_loop_manual")

_USE_COLOR = sys.stdout.isatty()
def _green(s): return f"\033[92m{s}\033[0m" if _USE_COLOR else s
def _red(s):   return f"\033[91m{s}\033[0m" if _USE_COLOR else s
def _bold(s):  return f"\033[1m{s}\033[0m"  if _USE_COLOR else s
def _dim(s):   return f"\033[2m{s}\033[0m"  if _USE_COLOR else s

_results: list[tuple[str, bool, str]] = []

def _pass(label, detail=""):
    print(f"  [{_green('PASS')}] {label}" + (f"  {_dim(detail)}" if detail else ""))
    _results.append((label, True, detail))

def _fail(label, detail=""):
    print(f"  [{_red('FAIL')}] {label}" + (f"\n         {_red(detail)}" if detail else ""))
    _results.append((label, False, detail))

def _section(title):
    print(f"\n{_bold(title)}")
    print("  " + "─" * (len(title) + 2))


# ---------------------------------------------------------------------------
# Synthetic OHLCV DataFrame factory
# ---------------------------------------------------------------------------

def _make_bars(symbol: str, n: int = 100, base_price: float = 200.0) -> pd.DataFrame:
    """
    Build a realistic-shaped 5-minute OHLCV DataFrame with:
    - Enough rows (100) for EMA-26, MACD, ATR-14, RSI-14 to initialise
    - Gentle uptrend + noise so indicators produce non-NaN values
    - Volume with realistic intraday variation
    - DatetimeIndex in UTC, 5-minute bars ending ~now
    """
    rng = np.random.default_rng(seed=abs(hash(symbol)) % (2**32))
    now = datetime.now(timezone.utc).replace(second=0, microsecond=0)
    # Build backwards from now in 5-minute steps
    times = [now - timedelta(minutes=5 * i) for i in range(n, 0, -1)]

    prices = [base_price]
    for _ in range(n - 1):
        prices.append(prices[-1] * (1 + rng.normal(0.0002, 0.003)))

    closes = np.array(prices)
    highs  = closes * (1 + rng.uniform(0.001, 0.006, n))
    lows   = closes * (1 - rng.uniform(0.001, 0.006, n))
    opens  = np.roll(closes, 1)
    opens[0] = closes[0]
    volumes = rng.integers(50_000, 500_000, n).astype(float)

    return pd.DataFrame({
        "open":   opens,
        "high":   highs,
        "low":    lows,
        "close":  closes,
        "volume": volumes,
    }, index=pd.DatetimeIndex(times, tz=timezone.utc))


# ---------------------------------------------------------------------------
# Mocks
# ---------------------------------------------------------------------------

def _build_mock_adapter(bars: dict[str, pd.DataFrame]):
    """Adapter that serves pre-built DataFrames instead of calling yfinance."""
    adapter = MagicMock()
    async def fetch_bars(symbol, interval, period):
        df = bars.get(symbol)
        if df is None:
            raise ValueError(f"No mock bars for {symbol}")
        return df
    adapter.fetch_bars = fetch_bars
    return adapter


def _build_mock_broker(order_id: str = "test-ord-001"):
    from ozymandias.execution.broker_interface import AccountInfo, OrderResult
    account = AccountInfo(
        equity=100_000.0, buying_power=80_000.0, cash=50_000.0,
        currency="USD", pdt_flag=False, daytrade_count=0, account_id="mock-001",
    )
    result = OrderResult(
        order_id=order_id,
        status="new",
        submitted_at=datetime.now(timezone.utc),
    )
    broker = MagicMock()
    broker.get_account  = AsyncMock(return_value=account)
    broker.place_order  = AsyncMock(return_value=result)
    return broker


def _seed_reasoning_cache(cache, tmpdir: Path) -> dict:
    """
    Write a plausible Claude reasoning result into the cache so
    load_latest_if_fresh() returns it.  Returns the parsed_response dict.
    """
    now_iso = datetime.now(timezone.utc).isoformat()
    parsed_response = {
        "timestamp":         now_iso,
        "market_assessment": "bullish",
        "risk_flags":        [],
        "position_reviews":  [],
        "watchlist_changes": {"add": [], "remove": [], "rationale": ""},
        "new_opportunities": [
            {
                "symbol":           "AAPL",
                "action":           "buy",
                "strategy":         "momentum",
                "timeframe":        "short",
                "conviction":       0.78,
                "suggested_entry":  210.0,
                "suggested_exit":   226.0,
                "suggested_stop":   199.5,
                "position_size_pct": 0.08,
                "reasoning":        "VWAP breakout on above-average volume",
            },
            {
                "symbol":           "TSLA",
                "action":           "buy",
                "strategy":         "momentum",
                "timeframe":        "short",
                "conviction":       0.65,
                "suggested_entry":  305.0,
                "suggested_exit":   328.0,
                "suggested_stop":   290.0,
                "position_size_pct": 0.07,
                "reasoning":        "Momentum continuation above 20-day EMA",
            },
        ],
    }
    cache.save(
        trigger="time_ceiling",
        input_context={"symbols": ["AAPL", "TSLA"]},
        raw_response=json.dumps(parsed_response),
        parsed_response=parsed_response,
    )
    return parsed_response


# ---------------------------------------------------------------------------
# State setup
# ---------------------------------------------------------------------------

async def _seed_state(orch) -> None:
    from ozymandias.core.state_manager import (
        ExitTargets, PortfolioState, Position,
        TradeIntention, WatchlistEntry, WatchlistState,
    )
    now_iso = datetime.now(timezone.utc).isoformat()

    watchlist = WatchlistState(entries=[
        WatchlistEntry(symbol="AAPL", date_added=now_iso,
                       reason="strong momentum", priority_tier=1),
        WatchlistEntry(symbol="TSLA", date_added=now_iso,
                       reason="volatility play", priority_tier=1),
        WatchlistEntry(symbol="NVDA", date_added=now_iso,
                       reason="monitoring", priority_tier=2),   # tier 2 — NOT scanned
    ])
    await orch._state_manager.save_watchlist(watchlist)

    portfolio = PortfolioState(
        cash=50_000.0,
        buying_power=80_000.0,
        positions=[
            Position(
                symbol="MSFT",
                shares=30,
                avg_cost=420.00,
                entry_date="2026-03-14",
                intention=TradeIntention(
                    strategy="momentum",
                    exit_targets=ExitTargets(profit_target=450.00, stop_loss=400.00),
                ),
            )
        ],
    )
    await orch._state_manager.save_portfolio(portfolio)


# ---------------------------------------------------------------------------
# Interceptors to observe internal state mid-cycle
# ---------------------------------------------------------------------------

_ta_results:      dict[str, dict] = {}
_entry_signals:   dict[str, list] = {}
_ranked_opps:     list            = []
_place_order_args: list           = []


def _install_interceptors(orch):
    """Monkey-patch key internal calls to capture their outputs for assertions."""
    from ozymandias.intelligence import technical_analysis as ta_mod
    from ozymandias.intelligence import opportunity_ranker as ranker_mod

    orig_summary = ta_mod.generate_signal_summary

    def traced_summary(symbol, df):
        result = orig_summary(symbol, df)
        _ta_results[symbol] = result
        return result

    ta_mod.generate_signal_summary = traced_summary
    # Patch the reference used inside orchestrator
    import ozymandias.core.orchestrator as orch_mod
    orch_mod.generate_signal_summary = traced_summary

    orig_rank = orch._ranker.rank_opportunities
    def traced_rank(*args, **kwargs):
        result = orig_rank(*args, **kwargs)
        _ranked_opps.clear()
        _ranked_opps.extend(result)
        return result
    orch._ranker.rank_opportunities = traced_rank


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def run() -> None:
    print(_bold("\n══ Medium Loop Manual Cycle ══"))
    print(_dim("  Watchlist: AAPL + TSLA (tier1), NVDA (tier2)  |  Portfolio: MSFT position"))
    print(_dim("  yfinance: mocked  |  Claude cache: seeded with 2 opportunities\n"))

    from ozymandias.core.orchestrator import Orchestrator
    from ozymandias.execution.broker_interface import AccountInfo

    # Pre-build synthetic DataFrames
    bars = {
        "AAPL": _make_bars("AAPL", base_price=210.0),
        "TSLA": _make_bars("TSLA", base_price=305.0),
        "MSFT": _make_bars("MSFT", base_price=428.0),
    }
    _section("Synthetic DataFrames")
    for sym, df in bars.items():
        print(f"  {sym}: {len(df)} rows  close={df['close'].iloc[-1]:.2f}  "
              f"vol={df['volume'].iloc[-1]:.0f}  index_tz={df.index.tz}")

    with tempfile.TemporaryDirectory() as tmpdir:
        stub_account = AccountInfo(
            equity=100_000.0, buying_power=80_000.0, cash=50_000.0,
            currency="USD", pdt_flag=False, daytrade_count=0, account_id="mock-001",
        )

        with (
            patch("ozymandias.execution.alpaca_broker.AlpacaBroker.__init__",
                  MagicMock(return_value=None)),
            patch("ozymandias.execution.alpaca_broker.AlpacaBroker.get_account",
                  AsyncMock(return_value=stub_account)),
            patch("ozymandias.execution.alpaca_broker.AlpacaBroker.get_market_hours",
                  AsyncMock(return_value=MagicMock(
                      is_open=True, session="regular",
                      next_open=datetime.now(timezone.utc) - timedelta(hours=1),
                      next_close=datetime.now(timezone.utc) + timedelta(hours=4),
                  ))),
            patch("anthropic.AsyncAnthropic", MagicMock),
            patch("ozymandias.core.orchestrator.Orchestrator._load_credentials",
                  MagicMock(return_value=("mock-key", "mock-secret"))),
        ):
            orch = Orchestrator()
            orch._state_manager._dir = Path(tmpdir)
            orch._reasoning_cache._dir = Path(tmpdir) / "cache"
            orch._reasoning_cache._dir.mkdir()
            await orch._startup()

        # Swap in mocks
        orch._broker       = _build_mock_broker()
        orch._data_adapter = _build_mock_adapter(bars)

        # Seed state and cache
        await _seed_state(orch)
        parsed_opps = _seed_reasoning_cache(orch._reasoning_cache, Path(tmpdir))

        # Intercept TA and ranker outputs
        _install_interceptors(orch)

        _section("Running _medium_loop_cycle()")
        exception_caught = None
        # Patch is_market_open in the orchestrator module so the ranker's hard
        # market-hours filter always passes regardless of the real clock.
        with patch("ozymandias.core.orchestrator.is_market_open", return_value=True):
            try:
                await orch._medium_loop_cycle()
            except Exception as exc:
                exception_caught = exc
                traceback.print_exc()

        # ── Assertions ──────────────────────────────────────────────────────
        _section("Results")

        # 1. No unhandled exception
        if exception_caught is None:
            _pass("_medium_loop_cycle() raised no unhandled exception")
        else:
            _fail("_medium_loop_cycle() raised", str(exception_caught))

        # 2. TA computed for exactly AAPL, TSLA, MSFT (not NVDA)
        scanned = set(_ta_results.keys())
        if scanned == {"AAPL", "TSLA", "MSFT"}:
            _pass("TA computed for correct symbol set (tier1 + position, no tier2)",
                  f"symbols={sorted(scanned)}")
        else:
            _fail("TA symbol set wrong", f"expected {{AAPL,TSLA,MSFT}}, got {scanned}")

        if "NVDA" in scanned:
            _fail("NVDA (tier2) incorrectly scanned")
        else:
            _pass("NVDA (tier2) correctly excluded from scan")

        # 3. TA signals are valid (no NaN composite scores)
        all_ok = True
        for sym, summary in _ta_results.items():
            score = summary.get("composite_technical_score")
            if score is None or (isinstance(score, float) and score != score):
                _fail(f"{sym} composite_technical_score is None/NaN", f"score={score}")
                all_ok = False
        if all_ok:
            _pass("All composite_technical_scores are valid floats")
            for sym, summary in _ta_results.items():
                print(f"    {sym}: score={summary['composite_technical_score']:.3f}  "
                      f"rsi={summary['signals'].get('rsi', 'N/A'):.1f}"
                      if isinstance(summary['signals'].get('rsi'), float) else
                      f"    {sym}: score={summary['composite_technical_score']:.3f}")

        # 4. Ranker produced results — key test: were the 2 Claude opportunities visible?
        if _ranked_opps:
            _pass(f"Ranker produced {len(_ranked_opps)} scored opportunity/ies",
                  f"scores={[round(o.composite_score,3) for o in _ranked_opps]}")
        else:
            _fail("Ranker produced 0 results — either hard filters blocked all "
                  "candidates, or Claude opportunities were not read from cache correctly")

        # 5. Specifically verify parsed_response was used (not the cache envelope).
        #    If the bug is present, new_opportunities will be empty and the ranker
        #    sees no candidates regardless of TA data.
        cache_hit = orch._reasoning_cache.load_latest_if_fresh()
        if cache_hit is not None:
            loaded_opps = cache_hit.get("parsed_response", {}).get("new_opportunities", [])
            if len(loaded_opps) == 2:
                _pass("Cache contains 2 opportunities under parsed_response key",
                      f"symbols={[o['symbol'] for o in loaded_opps]}")
            else:
                _fail("Cache parsed_response.new_opportunities unexpected",
                      f"got {len(loaded_opps)} entries")

            # Check what the orchestrator actually fed to the ranker
            top_level_opps = cache_hit.get("new_opportunities", [])
            if top_level_opps:
                _fail("CACHE BUG: orchestrator reads top-level new_opportunities directly — "
                      "should use cached_raw['parsed_response']",
                      f"top-level has {len(top_level_opps)} entries")
            else:
                # Verify the ranker DID see opportunities (i.e. orchestrator used parsed_response)
                if _ranked_opps:
                    _pass("Orchestrator correctly used cached_raw['parsed_response'] "
                          "— ranker saw Claude opportunities")
                else:
                    _fail("Ranker saw 0 candidates — orchestrator may have passed cache "
                          "envelope instead of parsed_response to _result_from_raw_reasoning()")
        else:
            _fail("load_latest_if_fresh() returned None — cache seeding failed")

        # 6. _latest_indicators populated for all 3 scanned symbols
        indicators = getattr(orch, "_latest_indicators", {})
        if set(indicators.keys()) == {"AAPL", "TSLA", "MSFT"}:
            _pass("_latest_indicators populated for all 3 scanned symbols")
        else:
            _fail("_latest_indicators wrong symbol set", f"got {set(indicators.keys())}")

        # 7. place_order / fill_protection interaction
        place_calls = orch._broker.place_order.call_count
        fp_orders   = orch._fill_protection.get_pending_orders()
        if place_calls == 0:
            # Might be fine — ranker filtered everything or risk blocked it
            _pass("No order placed (ranker filtered all candidates or risk blocked — "
                  "check logs above for reason)",
                  "acceptable if all hard-filter or risk-manager rejections are logged")
        else:
            placed_syms = [c.args[0].symbol for c in orch._broker.place_order.call_args_list]
            _pass(f"place_order called {place_calls} time(s)",
                  f"symbols={placed_syms}")
            if fp_orders:
                fp_syms = [o.symbol for o in fp_orders]
                _pass("FillProtectionManager has pending order(s) after entry",
                      f"symbols={fp_syms}")
            else:
                _fail("place_order was called but FPM has no pending orders — "
                      "record_order was not called after place_order")

        # 8. evaluate_position ran on MSFT without error (no exception = evidence)
        if exception_caught is None:
            _pass("evaluate_position() ran on MSFT without raising (no exception from cycle)")
        else:
            _fail("Cannot confirm evaluate_position — cycle raised an exception")

        # 9. Print ranked opportunity table
        if _ranked_opps:
            print(f"\n  Ranked opportunities:")
            for i, opp in enumerate(_ranked_opps, 1):
                print(f"    #{i} {opp.symbol:<6} composite={opp.composite_score:.3f}  "
                      f"ai={opp.ai_conviction:.2f}  tech={opp.technical_score:.2f}  "
                      f"strategy={opp.strategy}")

    # ── Summary ─────────────────────────────────────────────────────────────
    passed = sum(1 for _, ok, _ in _results if ok)
    failed = sum(1 for _, ok, _ in _results if not ok)
    total  = len(_results)
    print(f"\n{'─'*50}")
    status = (_green(f"ALL {total} ASSERTIONS PASSED") if failed == 0
              else _red(f"{failed}/{total} ASSERTIONS FAILED"))
    print(f"  {status}  ({passed} passed, {failed} failed)")
    print(f"{'─'*50}\n")
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(run())
